spring:
  application:
    name: java-spring-encrypt-password
  datasource:
    url: jdbc:h2:file:./data/mydb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

security:
  jwt:
    expiration: 86400
    key: 05099799-f97b-44ff-962f-9156dd248d2b
